// as visible in bitcoin.json cached market data
const FIAT = {
  usd: 'United States Dollar',
  eur: 'Euro',
  gbp: 'Pound sterling',
  cny: 'Chinese Yuan',
  aud: 'Australian Dollar',
  jpy: 'Japanese Yen',
  chf: 'Swiss Franc',
  cad: 'Canadian Dollar',
  czk: 'Czech Koruna',
  brl: 'Brazilian Real',
  hkd: 'Hong Kong Dollar',
  idr: 'Indonesian Rupiah',
  inr: 'Indian Rupee',
  rub: 'Russian Ruble',
  dkk: 'Danish Krone',
  huf: 'Hungarian Forint',
  ils: 'Israeli New Shekel',
  krw: 'South Korean won',
  bmd: 'Bermudan Dollar',
  aed: 'United Arab Emirates Dirham',
  ars: 'Argentine Peso',
  bdt: 'Bangladeshi Taka',
  clp: 'Chilean Peso',
  kwd: 'Kuwaiti Dinar',
  lkr: 'Sri Lankan Rupee',
  mmr: 'Myanmar Kyat',
  mxn: 'Mexican Peso',
  myr: 'Malaysian Ringgit',
  ngn: 'Nigerian Naira',
  nok: 'Norwegian Krone',
  nzd: 'New Zealand dollar',
  php: 'Philippine peso',
  pln: 'Poland złoty',
  sar: 'Saudi Riyal',
  sek: 'Swedish Krona',
  sgd: 'Singapore Dollar',
  thb: 'Thai Baht',
  try: 'Turkish lira',
  twd: 'New Taiwan dollar',
  uah: 'Ukrainian hryvnia',
  //vef: 'Bolívar Fuerte'
  vnd: 'Vietnamese dong',
  zar: 'South African Rand'
};

export default function getFiat(coinName) {
  return FIAT[coinName.toLowerCase()];
}
